# Generated by Django 4.2.1 on 2023-06-02 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=50)),
                ('umail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='dog',
            name='dogAge',
        ),
        migrations.AlterField(
            model_name='dog',
            name='dogOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.users_info'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
