# Generated by Django 4.2.1 on 2023-06-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='uName',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
